### ISSUE TITLE
Can not scroll the time

### ISSUE THREAD

**Issue by harisnaufal** [troberts-28/react-native-timer-picker#12]
Hi, ive been using your libs but i cant scroll it up or down both for ios and android. Would you mind to looking for it? Thanks in advance.

**Comment by troberts-28** [comment]
Hey! Would you mind sharing your code?

**Comment by troberts-28** [comment]
Hi @harisnaufal!

I recently made a change that addressed occasional unresponsiveness caused by the labels absorbing scroll events.

Are you still having problems?

If you are, I'd be keen to take a look at your code to resolve what's going wrong.
