### ISSUE TITLE
Missing AM and PM formats

### ISSUE THREAD

**Issue by fidaay** [troberts-28/react-native-timer-picker#16]
Hello, 

Are there any plans to implement AM and PM formats? I find out the package very complete but I feel that we really need the capability to chose between AM and PM.

**Comment by troberts-28** [comment]
Hey @fidaay 👋

I didn't have immediate plants to implement this, but could definitely prioritise it as it would be pretty easy to do.

What jumped to mind for me was:
- An additional boolean prop that lets you switch between 24hr and 12hr format (e.g. `is24hr`).
- There are then two ways of handling `is24hr={false}`:
  1. It could make the picker only show 0-12 and to show an additional picker/dropdown/switch that lets you switch between AM/PM (would need to expose all the props necessary to make the styling / layout of that AM/PM picker completely flexible)
  2. The hour picker could scroll continuously between 0-11am and then 12pm - 11pm (so it works the same way as it currently does, but just formats the options differently). I'd expose separate styling props for the am/pm labels so those could be styled flexibly.

What would work best for your use case?

**Comment by fidaay** [comment]
Hi, thank you for your quick response, it's a good sign because it tells me that you really care. From my side, I think that the second option would be the best one as it can be perceived as more natural.

**Comment by troberts-28** [comment]
Nice! I was leaning towards that one as I typed out the two options and properly though them through.

I should be able to add this in the next couple of weeks!

**Comment by troberts-28** [comment]
https://github.com/troberts-28/react-native-timer-picker/assets/72606459/c6381ca3-7818-4775-b5d3-c50ce5d85ac0

Progress so far! ⚡

**Comment by troberts-28** [comment]
@fidaay just pushed this feature in v1.4.0 - try it out and let me know what you think!
