### ISSUE TITLE
Feature request: Change gap in between numbers

### ISSUE THREAD

**Issue by fredrikburmester** [troberts-28/react-native-timer-picker#19]
<img width="271" alt="Screenshot 2024-02-29 at 12 29 44" src="https://github.com/troberts-28/react-native-timer-picker/assets/26228321/f535bd04-ea10-4a4b-a0df-f46693a25bb6">

Is there a way (or could you implement a way) to decrease the padding in between the numbers?
Both vertically and horizontally.

Thanks!

**Comment by troberts-28** [comment]
Hey @fredrikburmester!

This is possible by adjusting the width of the `pickerItemContainer` in the styles property. For example:

`styles={{
                        pickerItemContainer: {
                            width: 100
                        },
                    }}`
                    
You will also likely need to adjust the styles of `pickerLabelContainer` to re-align the labels. They're absolutely positioned so you'll need to adjust `top/bottom/left/right`. There is a minor limitation with the current release that stops those labels overflowing their container; I'll release a patch today that addresses that.

Here's a full example of a `TimerPicker` with a narrower width and the labels centred and adjusted.
```typescript
<TimerPicker
    padWithNItems={2}
    hourLabel=":"
    minuteLabel=":"
    secondLabel=""
    LinearGradient={LinearGradient}
    styles={{
        theme: "light",
        pickerItem: {
            fontSize: 34,
        },
        pickerLabel: {
            fontSize: 32,
            marginTop: 0,
        },
        pickerContainer: {
            marginRight: 6,
        },
        pickerItemContainer: {
            width: 100,
        },
        pickerLabelContainer: {
            right: -20,
            top: 0,
            bottom: 6,
            width: 40,
            alignItems: "center",
        },
    }}
/>;

```

**Comment by troberts-28** [comment]
No there isn't, but there should be! I'll put out another release this weekend that adds those props and the ability to add styling for the picker when in the disabled state.

**Comment by troberts-28** [comment]
Hey @fredrikburmester, I've added that feature. There's three props (one for each picker):
- `hoursPickerIsDisabled`
- `minutesPickerIsDisabled`
- `secondsPickerIsDisabled`

You can adjust the styling of a disabled picker with the style prop `disabledPickerContainer`. The default is `{opacity: 0.4}`.

Let me know if that fits the bill!
