### ISSUE TITLE
Question: Can I use it in my Next.js project?

### ISSUE THREAD

**Issue by MSR-07** [troberts-28/react-native-timer-picker#21]
Basically  I develop Progressive Web Applications in Next.js and need to implement a time picker. So, I'm hoping someone can suggest a solution.

**Comment by troberts-28** [comment]
Hey @MSR-07!

Sadly no, this won't work in your Next.js project.

It technically works in React Native for Web, but I haven't configured it for web. See [Expo snack](https://snack.expo.dev/@nuumi/react-native-timer-picker-demo)  - the snap to index doesn't work and you can't drag to scroll. I'd consider configuring it for web if there was good appetite for it!

**Comment by MSR-07** [comment]
Hey @troberts-28 
Thank you very much for your prompt response! Your insights have been extremely helpful and I truly appreciate the time you have taken to provide them.
