### ISSUE TITLE
Feature Request: Add Tick Sound or Vibration for iOS Picker-like Feedback

### ISSUE THREAD

**Issue by usama23sep** [troberts-28/react-native-timer-picker#22]
https://github.com/troberts-28/react-native-timer-picker/assets/56351501/463f947f-37eb-4d63-9234-fb416adf2267

### Feature Request

I would like to propose the addition of a tick sound or vibration feedback option for user interfaces, similar to the iOS picker experience. This feature would enhance user interaction by providing subtle auditory or haptic feedback when scrolling through options or making selections, improving overall user experience and accessibility.

**Comment by troberts-28** [comment]
Hey @usama23sep 👋

This would be a really nice adition. I'll put it on the roadmap!

**Comment by troberts-28** [comment]
Hey @usama23sep, this has just been released in v1.8.0 ✨ Check the updated docs for how to enable it. 

N.B. I've only configured it for Expo so far
