### ISSUE TITLE
formatTime missing from examples

### ISSUE THREAD

**Issue by callum-gander** [troberts-28/react-native-timer-picker#28]
Hi,

In the examples you give, there's a `formatTime` function being called, but this is never imported or defined. Could this be clarified in the examples? Either by importing it or defining what this `formatTime` is expected to look like, obviously I'm guessing it will vary and be dictated by the user but having an example within the example would improve the quality of the docs. 

Thanks, great package btw

**Comment by troberts-28** [comment]
Hey @callum-gander 👋

This is a great shout. You're right that the `formatTime` function is just a utility function to display the selected time, but it would absolutely make the examples more complete if it were included. Will add it in 🙌

**Comment by callum-gander** [comment]
Perfect! Thanks for the quick response 🙌
