### ISSUE TITLE
Configuration Request: Add possibility to configure padNumbersWithZero

### ISSUE THREAD

**Issue by kocelke1** [troberts-28/react-native-timer-picker#31]
In case of minutes and seconds, single digits are padded with zero by default. But currently there is no option for hours to be padded with zero.
Please make it configurable by giving some control to TimerPicker for padNumbersWithZero prop of each DurationScroll, instead of the current setup with hardcoded boolean values.
Thank you in advance.

**Comment by troberts-28** [comment]
Hey @kocelke1,

Thank you for the great suggestion! Will add this to the library in the coming weeks, or feel free to submit a PR if you'd like it added sooner 🚀

**Comment by kocelke1** [comment]
Thank you for your response, no rush needed.

**Comment by troberts-28** [comment]
Hey @kocelke1, all done 🙌

Upgrade to `v1.10.1` to use the new props:
- `padHoursWithZero`
- `padMinutesWithZero`
- `padSecondsWithZero`
