### ISSUE TITLE
Native look

### ISSUE THREAD

**Issue by andredewaard** [troberts-28/react-native-timer-picker#36]
Is it possible, or does someone already made some styles to make it look more native like this [package](https://www.npmjs.com/package/react-native-date-picker) does?

<img width="293" alt="Screenshot 2024-08-08 at 11 03 52" src="https://github.com/user-attachments/assets/d9d335b2-025e-47bb-95bf-275d8bb3951e">

**Comment by troberts-28** [comment]
It's definitely possible to style it to look more native by supplying custom styling under the `styles` prop (you could make it look similar to both the native iOS and Android looks). We'll see if someone might be able to help you out with some examples?

There's currently no way to achieve the 'squished' look of the numbers above and below the picker, as in the screenshot you shared. To achieve that, we'd need use the React Native Animated API and scale each item in the picker based on its position in the viewport. It's possible but isn't on the roadmap right now.

**Comment by troberts-28** [comment]
Hey @andredewaard, there hasn't been any activity on this issue for a while. If there are no further updates or discussions in the next 2 weeks, I'll close this issue to keep the repository tidy. Please let me know if this is still relevant or if there are any updates. Thanks!
