### ISSUE TITLE
does react-native-timer-picker works in New Architecture?

### ISSUE THREAD

**Issue by inthisar-hamza** [troberts-28/react-native-timer-picker#37]
I tried it in new architecture but doesnt work, shows unsupport message? does this lib works on new arch?

**Comment by troberts-28** [comment]
Hey @inthisar-hamza 🙌

Thanks for raising this. I haven't yet tried running it on the new architecture so I'm not surprised it doesn't work!

I will put this on the roadmap, but feel free to submit a PR if you have the time. I don't imagine it would be a major piece of work to make it work on the new architecture.

**Comment by inthisar-hamza** [comment]
@troberts-28 can you provide an estimated duration, if that is possible, required for my project Hackathon

**Comment by troberts-28** [comment]
I won't have time work on this for at least a couple of weeks unfortunately. Best of luck with the Hackathon!

**Comment by troberts-28** [comment]
Hey @inthisar-hamza, the library has now been made fully compatible with the new architecture in `v2.0.0` 🙌
